using System;
using System.IO;
using RestSharp;
using RestSharp.Authenticators;
using System.Collections.Generic;
using TagTool.Data.Models;
using TagTool.Data.Secrets;

namespace TagTool.Data.Services
{
    public class EmailService
    {
        public static IRestResponse SendMessage (IList<User> MailList, Report report, String City)
        {  
            // Setup
            RestClient client = new RestClient ();
            client.BaseUrl = new Uri ("https://api.eu.mailgun.net/v3/");
            client.Authenticator =
                new HttpBasicAuthenticator ("api", GetKey.MailgunAPIKey());
            // Create To list
            string ToField = "";
            foreach (User u in MailList)
            {
                ToField += u.EmailAddress + ", ";
            }
        

            // Create Message
            string text = WriteMessage(report, City);
                
            // Domain
            string DomainName = "helpinghandni.tech";

            // The Request
            RestRequest request = new RestRequest ();
            request.AddParameter ("domain", DomainName, ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter ("from", "HelpingHand Developer <mailgun@" + DomainName +">");
            request.AddParameter ("to", ToField);
            request.AddParameter ("subject", "New Homeless Report in your City!");
            request.AddParameter ("text", text);
            request.Method = Method.POST;
            return client.Execute (request);
        }

        private static string WriteMessage(Report report, string City)
        {
            return "A new Report has been created in " + 
                City +
                ". The Three word address of the report is: " +
                report.ThreeWordAddress + 
                ". To view on a map open:\n https://what3words.com/" + 
                report.ThreeWordAddress + 
                "\n This report was created at " + report.CreatedAt.ToString() +
                ", and the following was the additional information provided: " +
                report.AdditionalInfo + 
                "\n\n Thank you! \n This message was auto-generated by HelpingHand" +
                " & sent via MailGun. \nIf you want to stop recieving these" +
                " messages, please turn off notifications in your account settings.";
        }
    }

}